name: Python Tests

# Bestimme, wann der Workflow ausgeführt werden soll (z.B. bei push und pull_request Events).
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest  # Wähle ein Betriebssystem (hier Ubuntu)

    strategy:
      matrix:
        python-version: [3.10,3.12]  # Teste das Projekt mit verschiedenen Python-Versionen

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # Checkt den Code aus dem Repository aus

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4  # Richtet Python in der angegebenen Version ein
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          
      - name: Run tests
        run: |
          python -m unittest discover  # Führt Unittest-Tests aus